;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Dec 2019
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
CODE    			SEGMENT PARA 'CODE'
					ASSUME CS:CODE, DS:DATA, SS:STAK
STAK    			SEGMENT PARA STACK 'STACK'
					DW 20 DUP(?)
STAK    			ENDS

DATA    			SEGMENT PARA 'DATA'

DATA    			ENDS

START PROC FAR
        MOV AX, DATA
		MOV DS, AX	
		
		COUNTER0 EQU 078H
		COUNTER1 EQU 07AH
		COUNTER2 EQU 07CH
		CW       EQU 07EH
		
		MOV DX, CW
		
		MOV AL, 00110111b ; counter0, msb+lsb, mod3, bcd
		OUT CW, AL
		
		MOV AL, 01110111b ; counter1, msb+lsb, mod3, bcd
		OUT CW, AL
		
		MOV AL, 00h
		OUT COUNTER0, AL
		MOV AL, 10h
		OUT COUNTER0, AL
		
			
		MOV AL, 00h
		OUT COUNTER1, AL
		MOV AL, 05h
		OUT COUNTER1, AL

		
		ENDLESS:			
		NOP
		JMP ENDLESS
	
RETF
START ENDP
	

	
CODE    ENDS
        END START