;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Eki 18 2019
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

STACK		SEGMENT PARA STACK 'STACK'
			DW 20 DUP(?)
STACK		ENDS

DATA		SEGMENT PARA 'DATA'
arr			DB 03Fh, 006h, 05Bh, 04Fh, 066h, 06Dh, 07Dh, 007h, 07Fh, 06Fh ;0,1,2,3,4,5,6,7,8,9
DATA		ENDS

CODE    	SEGMENT PUBLIC 'CODE'
			ASSUME CS:CODE, DS:DATA, SS:STACK
		
START:

			   


PORTA    EQU 68H
PORTB    EQU 6AH
PORTC    EQU 6CH
PORT_CW  EQU 6EH



				 MOV AX, DATA
				 MOV DS, AX
				 
      

;Writing Control Word	  
;====================================================================		
				MOV DX, PORT_CW		
				MOV AL, 090H   ;PortA: (input), PortB: (output), PortC: (output)
				OUT DX, AL
;====================================================================	


;Check push buttons
;====================================================================
WAITING:			MOV DX, PORTB
				MOV AL, 00000000B
				OUT DX, AL


				MOV DX, PORTA
				IN AL, DX
				CMP AL, 00h
				JE WAITING
;====================================================================
				
				
				MOV DI, 01h
CONTROL:		TEST AX, DI
				JNZ LABELX
				SHL DI, 1
				JMP CONTROL
			
				
			
;Button pushed					
;====================================================================
LABELX: 			MOV DX, PORTB
				MOV AL, arr[DI]
				OUT DX, AL
				
;Disable two or more pushed button					
;====================================================================				
				IN AL, PORTA
				CMP AL, 00h
				JE WAITING
				JMP LABELX
;====================================================================

				
		     


CODE    ENDS
        END START
